version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5555:5555"
    depends_on:
      - mongodb
    networks:
      - my_network

  mongodb:
    image: mongo
    environment:
      MONGO_URI: "mongodb://mongodb:27017/project_db"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network
    expose:
      - 27017

volumes:
  mongodb_data:

networks:
  my_network:
